
create sequence LEDGER_SEQUENCE;
create sequence CUSTOMER_SEQUENCE start 1;
create sequence  ACCOUNT_SEQUENCE;

create table CUSTOMERS (
	CUSTOMER_ID		INTEGER PRIMARY KEY DEFAULT nextval('CUSTOMER_SEQUENCE'),
	FIRST_NAME		VARCHAR(50) NOT NULL,
	FAMILY_NAME		VARCHAR(50) NOT NULL,
	USER_NAME		VARCHAR(20) NOT NULL,
	SECRET			VARCHAR(40) NOT NULL
);

create table ADDRESSES (
	CUSTOMER_ID 	INTEGER REFERENCES CUSTOMERS(CUSTOMER_ID),
	ADDRESS_TYPE	VARCHAR(10) NOT NULL,
	ADDRESS			VARCHAR(100) NOT NULL,
	TOWN			VARCHAR(50) NOT NULL,
	POST_CODE		VARCHAR(20) NOT NULL,
	STATE			VARCHAR(50) NOT NULL
);

create table ACCOUNTS (
	ACCOUNT_NUMBER	INTEGER PRIMARY KEY DEFAULT nextval('ACCOUNT_SEQUENCE'),
	CUSTOMER_ID		INTEGER REFERENCES CUSTOMERS(CUSTOMER_ID),
	ACCOUNT_TYPE	VARCHAR(10) NOT NULL,
	CURRENCY		VARCHAR(3) NOT NULL,
	BALANCE			DECIMAL(10,2) NOT NULL DEFAULT 0.0,
	ASOFENTRY		INTEGER NOT NULL,
	ASOFDATE		DATE NOT NULL
);

create table LEDGER (
	ENTRY_ID	INTEGER PRIMARY KEY DEFAULT nextval('LEDGER_SEQUENCE'),
	ACCOUNT_ID	VARCHAR(20) REFERENCES ACCOUNTS(ACCOUNT_ID),
	ENTRY_DATE	DATE NOT NULL,
	DEPOSIT		DECIMAL(10,2),
	WITHDRAWAL	DECIMAL(10,2)
);
